.TH "testgearctl" "1" "12 October 2014"

.SH "NAME"
testgearctl \- The Test Gear control application.

.SH "SYNOPSIS"
.PP
.B testgearctl
[<options>] <filename>

.SH "DESCRIPTION"
.PP
Run Test Gear lua test script.

.SH "OPTIONS"

.TP
.B \-i, \--interactive

Enable interactive mode.
.TP
.B \-s, \--stop-on-failure

Stop on failure.
.TP
.B \-v, \--version

Display program version.
.TP
.B \-h, \--help

Display help.

.SH "AUTHOR"
.PP
Written by Martin Lund <martin.lund@keep-it-simple.com>.
